"""fixed attribute name

Revision ID: 11938d85ddba
Revises: b894a2440ca3
Create Date: 2025-05-05 10:02:25.271584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11938d85ddba'
down_revision = 'b894a2440ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
