"""redid task model

Revision ID: 1d67c6e1c9ea
Revises: 11938d85ddba
Create Date: 2025-05-05 10:04:36.541975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d67c6e1c9ea'
down_revision = '11938d85ddba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
